# Generated by Django 4.2.7 on 2025-11-03 06:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='location_details',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain_name',
        ),
        migrations.AddField(
            model_name='field',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='field',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'VOLUNTEER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.IntegerField(default=55, help_text='Match duration in minutes'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='validated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'SCORING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_duration',
            field=models.IntegerField(default=55, help_text='Default match duration in minutes'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players_per_team',
            field=models.IntegerField(default=15, help_text='Maximum players allowed per team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('PENDING_VALIDATION', 'Pending Validation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed'), ('FORFEITED', 'Forfeited')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DIRECTOR', 'Tournament Director'), ('CAPTAIN', 'Team Captain'), ('PLAYER', 'Player'), ('VOLUNTEER', 'Volunteer/Field Official'), ('SCORING', 'Scoring Team'), ('SPONSOR', 'Sponsor/Partner'), ('FAN', 'Spectator/Fan')], default='FAN', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='match_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tournaments.match')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='sponsor_banners/')),
                ('website_url', models.URLField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_tournaments', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_sponsors', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'unique_together': {('tournament', 'sponsor')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('REQUESTED', 'Requested to Join'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.team')),
            ],
            options={
                'ordering': ['jersey_number', 'player__username'],
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='SpiritScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_knowledge', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('fouls_body_contact', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('fair_mindedness', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('positive_attitude', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('communication', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('total_score', models.IntegerField(default=10)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirit_scores_received', to='tournaments.team')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirit_scores_given', to='tournaments.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirit_scores', to='tournaments.match')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_spirit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('match', 'from_team', 'for_team')},
            },
        ),
    ]
