# Generated by Django 5.2.7 on 2025-11-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('total_children', models.IntegerField(default=0)),
                ('total_coaches', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('avg_assessment_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
